AWSTemplateFormatVersion: '2010-09-09'

Description: WebApp Template

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to run app
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet to launch EC2
  AMIID:
    Type: String
    Description: AMI ID for the EC2 instance
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type
  BranchName:
    Type: String
    Default: main
    Description: Branch name for the application code

Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  VMInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIID
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref InstanceSG

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub webapp-exercise-${BranchName}

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "*:*"
                Resource: "*"

Outputs:
  InstancePublicIP:
    Description: get pub ip
    Value: !GetAtt VMInstance.PublicIp
    Export:
      Name: InstancePublicIP

  InstancePrivateIP:
    Description: get priv ip
    Value: !GetAtt VMInstance.PrivateIp
    Export:
      Name: InstancePrivateIP

  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: BucketName
